name: 'youtubeanchorfm'

on:
  push:
    paths: 
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: youtubeanchorfm
        uses: Schrodinger-Hat/youtube-to-anchorfm@v1.0.3
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          EPISODE_PATH: /github/workspace
          LOAD_THUMBNAIL: true
          URL_IN_DESCRIPTION: true
          SET_PUBLISH_DATE: true
